### get all posts
GET http://localhost:3000/posts

### get post by id
GET http://localhost:3000/posts/6965e7aeff9789aa54187596

### get posts by sender
GET http://localhost:3000/posts?sender=6965e6efff9789aa5418758f

### update a post
PUT http://localhost:3000/posts/6965e7aeff9789aa54187596 
Content-Type: application/json

{
"content": "updated post"
}

### new Post 
POST http://localhost:3000/posts 
Content-Type: application/json

{
"senderId": "6965e6efff9789aa5418758f", 
"content": "new post"
}
###

GET http://localhost:3000/comments

###

###

GET http://localhost:3000/comments?postId=64b7f8e2c9e77a6f4d2e8b9a

###

###

GET http://localhost:3000/comments/64b8f0e2c9e77a6f4d2e8b9c

###

###
POST http://localhost:3000/comments
Content-Type: application/json

{
  "content": "This is a sample comment.",
  "postId": "64b7f8e2c9e77a6f4d2e8b9a",
  "senderId": "64b7f8e2c9e77a6f4d2e8b9b"
}   
###

###

PUT http://localhost:3000/comments/64b8f0e2c9e77a6f4d2e8b9c
Content-Type: application/json

{
  "content": "This is an updated comment."
}           

###

DELETE http://localhost:3000/comments/69653ce4bd38d2cd80121d6c

###     
